import type { NextPage } from 'next'
import Head from 'next/head'

const Home: NextPage = () => {
  return (
    <div className={"App"}>
      <Head>
          <title>Next TailwindCSS Boilerplate</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
      </Head>


      <main className={"h-screen w-screen overflow-auto flex flex-col justify-center items-center"}>
          <div className={"mb-4 text-4xl font-bold"}>NextJS TailwindCSS Boilerplate</div>
          <p>Boilerplate application bootstrap using NextJS, and TailwindCSS.</p>
          <p>Made using Typescript.</p>
      </main>
    </div>
  )
}

export default Home;
